# Generated by Django 5.2.10 on 2026-01-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_role_can_manage_security_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamposition',
            name='role_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_positions', to='users.role'),
        ),
    ]
