# Generated by Django 5.2.10 on 2026-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_role_can_manage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
