# Generated by Django 5.2.10 on 2026-01-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quizattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(blank=True, default='You are about to enter a proctored assessment environment. Please ensure your surroundings are compliant with standard evaluation protocols.'),
        ),
    ]
